openapi: 3.0.1
info:
  title: empacotamento
  description: ''
  version: 1.0.0
tags: []
paths:
  /pack-order:
    post:
      summary: Verificar empacotamento de produtos
      deprecated: false
      description: Rota que revebe uma lista de ordens, com seus items e dimensões, e retorna um conjunto de caixas
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pedidos:
                  type: array
                  items:
                    type: object
                    properties:
                      pedido_id:
                        type: number
                      produtos:
                        type: object
                        properties:
                          product_id:
                            type: string
                          dimensoes:
                            type: object
                            properties:
                              altura:
                                type: number
                              largura:
                                type: number
                              comprimento:
                                type: number
            examples:
              exemplo 1:
                value: 
                  pedidos:
                    - pedido_id: 1
                      produtos:
                        - produto_id: PS5
                          dimensoes:
                            altura: 40
                            largura: 10
                            comprimento: 25
                        - produto_id: Volante
                          dimensoes:
                            altura: 40
                            largura: 30
                            comprimento: 30
                    - pedido_id: 2
                      produtos:
                        - produto_id: Joystick
                          dimensoes:
                            altura: 15
                            largura: 20
                            comprimento: 10
                        - produto_id: Fifa 24
                          dimensoes:
                            altura: 10
                            largura: 30
                            comprimento: 10
                        - produto_id: Call of Duty
                          dimensoes:
                            altura: 30
                            largura: 15
                            comprimento: 10
                    - pedido_id: 3
                      produtos:
                        - produto_id: Headset
                          dimensoes:
                            altura: 25
                            largura: 15
                            comprimento: 20
                    - pedido_id: 4
                      produtos:
                        - produto_id: Mouse Gamer
                          dimensoes:
                            altura: 5
                            largura: 8
                            comprimento: 12
                        - produto_id: Teclado Mecânico
                          dimensoes:
                            altura: 4
                            largura: 45
                            comprimento: 15
                    - pedido_id: 5
                      produtos:
                        - produto_id: Cadeira Gamer
                          dimensoes:
                            altura: 120
                            largura: 60
                            comprimento: 70
                    - pedido_id: 6
                      produtos:
                        - produto_id: Webcam
                          dimensoes:
                            altura: 7
                            largura: 10
                            comprimento: 5
                        - produto_id: Microfone
                          dimensoes:
                            altura: 25
                            largura: 10
                            comprimento: 10
                        - produto_id: Monitor
                          dimensoes:
                            altura: 50
                            largura: 60
                            comprimento: 20
                        - produto_id: Notebook
                          dimensoes:
                            altura: 2
                            largura: 35
                            comprimento: 25
                    - pedido_id: 7
                      produtos:
                        - produto_id: Jogo de Cabos
                          dimensoes:
                            altura: 5
                            largura: 15
                            comprimento: 10
                    - pedido_id: 8
                      produtos:
                        - produto_id: Controle Xbox
                          dimensoes:
                            altura: 10
                            largura: 15
                            comprimento: 10
                        - produto_id: Carregador
                          dimensoes:
                            altura: 3
                            largura: 8
                            comprimento: 8
                    - pedido_id: 9
                      produtos:
                        - produto_id: Tablet
                          dimensoes:
                            altura: 1
                            largura: 25
                            comprimento: 17
                    - pedido_id: 10
                      produtos:
                        - produto_id: HD Externo
                          dimensoes:
                            altura: 2
                            largura: 8
                            comprimento: 12
                        - produto_id: Pendrive
                          dimensoes:
                            altura: 1
                            largura: 2
                            comprimento: 5


      responses:
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    pedido_id:
                      type: number
                    caixas:
                      type: array
                      items:
                        type: object
                        properties:
                          caixa_id:
                            type: string
                          produtos:
                            type: array
                            items:
                              type: string
                        
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
security: []
